/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell' at '17-5-15 上午9:54' with Gradle 2.14.1
 *
 * @author dell, @date 17-5-15 上午9:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
